"""Shared application constants."""

from __future__ import annotations

HOUR_FRAC = 0.25
TARIFF_THRESHOLD = 2500.0

AGENT_HISTORY_STRATEGY_LAST_MESSAGES = "last_messages"
AGENT_HISTORY_STRATEGY_LAST_TURNS = "last_turns"
AGENT_HISTORY_STRATEGY_TOKEN_BUDGET = "token_budget"
AGENT_HISTORY_STRATEGY_SUMMARY = "summary"
AGENT_HISTORY_STRATEGIES = [
    AGENT_HISTORY_STRATEGY_LAST_MESSAGES,
    AGENT_HISTORY_STRATEGY_LAST_TURNS,
    AGENT_HISTORY_STRATEGY_TOKEN_BUDGET,
    AGENT_HISTORY_STRATEGY_SUMMARY,
]

ASIMPLEX_AGENT_HISTORY_MAX_MESSAGES = 12
ASIMPLEX_AGENT_HISTORY_MAX_TURNS = 4
ASIMPLEX_AGENT_HISTORY_MAX_TOKENS = 2000
ASIMPLEX_AGENT_HISTORY_STRATEGY = AGENT_HISTORY_STRATEGY_LAST_MESSAGES

CHAT_AGENT_STR_FOR_DISPLAY = "Chat Agent"
CHAT_AGENT_STR_FOR_LOGGING = "chat_agent"
